### ISSUE TITLE
Compilation error 2.1.2

### ISSUE THREAD

**Issue by cld-kng** [ip2location/magento2-ip2location-countrystateblocker#2]
Magento CLI version 2.1.2

	

IP2Location\CountryStateBlocker\Helper\Data
		Incorrect dependency in class IP2Location\CountryStateBlocker\Helper\Data in /www/www/magento2/app/code/IP2Location/IP2Location_CountryStateBlocker/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	IP2Location\CountryStateBlocker\Helper\Data
		Incorrect dependency in class IP2Location\CountryStateBlocker\Helper\Data in /www/www/magento2/app/code/IP2Location/IP2Location_CountryStateBlocker/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	IP2Location\CountryStateBlocker\Helper\Data
		Incorrect dependency in class IP2Location\CountryStateBlocker\Helper\Data in /www/www/magento2/app/code/IP2Location/IP2Location_CountryStateBlocker/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	IP2Location\CountryStateBlocker\Helper\Data
		Incorrect dependency in class IP2Location\CountryStateBlocker\Helper\Data in /www/www/magento2/app/code/IP2Location/IP2Location_CountryStateBlocker/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	IP2Location\CountryStateBlocker\Helper\Data
		Incorrect dependency in class IP2Location\CountryStateBlocker\Helper\Data in /www/www/magento2/app/code/IP2Location/IP2Location_CountryStateBlocker/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	IP2Location\CountryStateBlocker\Helper\Data
		Incorrect dependency in class IP2Location\CountryStateBlocker\Helper\Data in /www/www/magento2/app/code/IP2Location/IP2Location_CountryStateBlocker/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	IP2Location\CountryStateBlocker\Helper\Data
		Incorrect dependency in class IP2Location\CountryStateBlocker\Helper\Data in /www/www/magento2/app/code/IP2Location/IP2Location_CountryStateBlocker/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	IP2Location\CountryStateBlocker\Helper\Data
		Incorrect dependency in class IP2Location\CountryStateBlocker\Helper\Data in /www/www/magento2/app/code/IP2Location/IP2Location_CountryStateBlocker/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	IP2Location\CountryStateBlocker\Helper\Data
		Incorrect dependency in class IP2Location\CountryStateBlocker\Helper\Data in /www/www/magento2/app/code/IP2Location/IP2Location_CountryStateBlocker/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1

I tried for a while but don't have the time to fix atm, looks trivial

**Comment by ip2location-com** [comment]
Hi, please follow the instructions given in README and install the version 1.0.1.
