### ISSUE TITLE
Allow Store Access from only one Country-State

### ISSUE THREAD

**Issue by Vikram0811** [ip2location/magento2-ip2location-countrystateblocker#3]
Hi,

I have installed your extension in Magento version 2.2 and could not figure out below configuration settings in admin. **I need to allow store access from a single country-state and restrict access from all other country and its states.**

![geolocation](https://user-images.githubusercontent.com/4048181/34143660-cd93851a-e4b3-11e7-85c9-56b366a21514.png)

For the above screenshot what values will go for the input fields **From** and **To** ?

![geoip-db](https://user-images.githubusercontent.com/4048181/34143701-02d86010-e4b4-11e7-8262-de0248fa63d2.png)

For the above screenshot, what value will go for input field Database Location ?

Thanks.

**Comment by ip2location-com** [comment]
Hi, it's not possible to do invert selection at this moment. You can only set rules to match the specified country/state.
