### ISSUE TITLE
Where is the IP2Location LITE DB1 file saved?

### ISSUE THREAD

**Issue by hunkguo** [ip2location/magento2-ip2location-countrystateblocker#4]

**Comment by ip2location-com** [comment]
You can save the file any where on your server but make sure it's accessible by your web server.

Then you can configure the path under Store > Configuration > IP2Location Country-State Blocker > Settings.

**Comment by hunkguo** [comment]
My bin file save in ./pub/static 
Database Location: ./pub/static/IP2LOCATION-LITE-DB1.BIN

It is OK.

But,My configuration does not work.I want to block IP from a country.

Origins:country
Mode:Equals To
From:"/" or "*"
To:null
code:404
status:enabled

**Comment by ghost** [comment]
Extension and redirect doesn't working on magento 2.2.5
